# UTS-Data-Mining
library(psych)
library(readr)
library(readxl)
data_akbilgic_edited21 <- read_excel("F:/Semester 5/Data Mining/data_akbilgic_edited21.xlsx")
View(data_akbilgic_edited21)
pairs.panels(data_akbilgic_edited21)
str(data_akbilgic_edited21)
modelreg21 <- lm(ISE~., data=data_akbilgic_edited21)
summary(modelreg21)
coefficients(modelreg21)

data_akbilgic_edited22 <- read_excel("F:/Semester 5/Data Mining/data_akbilgic_edited22.xlsx")
View(data_akbilgic_edited22)
pairs.panels(data_akbilgic_edited22)
str(data_akbilgic_edited22)
modelreg22 <- lm(ISE~., data=data_akbilgic_edited22)
summary(modelreg22)
coefficients(modelreg22)

data_akbilgic_edited23 <- read_excel("F:/Semester 5/Data Mining/data_akbilgic_edited23.xlsx")
View(data_akbilgic_edited23)
pairs.panels(data_akbilgic_edited23)
str(data_akbilgic_edited23)
modelreg23 <- lm(ISE~., data=data_akbilgic_edited23)
summary(modelreg23)
coefficients(modelreg23)

data_akbilgic_edited24 <- read_excel("F:/Semester 5/Data Mining/data_akbilgic_edited24.xlsx")
View(data_akbilgic_edited24)
pairs.panels(data_akbilgic_edited24)
str(data_akbilgic_edited24)
modelreg24 <- lm(ISE~., data=data_akbilgic_edited24)
summary(modelreg24)
coefficients(modelreg24)

data_akbilgic_edited2 <- read_csv("F:/Semester 5/Data Mining/data_akbilgic_edited2.csv")
View(data_akbilgic_edited2)
pairs.panels(data_akbilgic_edited2)
str(data_akbilgic_edited2)
modelreg2 <- lm(ISE~., data=data_akbilgic_edited2)
summary(modelreg2)
coefficients(modelreg2)
